# Ejercicios Python 2

Resuelve cada ejercicio en su celda y añade las pruebas necesarias para comprobar que funciona correctamente. Indica en un comentario la dificultad encontrada (del 1 al 5).

In [3]:
# Función que recibe una lista y devuelve otra eliminando sus duplicados (función y pruebas)
import numpy as np

def eliminarDuplicados(lista):
    return np.unique(lista)


print(eliminarDuplicados([1,2,3,4,5,2,3,4,5,3,4,5,4,5,5]))
print(eliminarDuplicados(['gato', 'pez', 'perro', 'pez', 'perro', 'gallina', 'perro']))

[1 2 3 4 5]
['gallina' 'gato' 'perro' 'pez']


In [22]:
# Función que recibe una matriz (una lista de listas) y devuelve otra eliminando sus duplicados

import numpy as np

# Sin elementos repetidos en las filas
def eliminarDuplicadosMatriz1(matriz):
    aux = []
    for fila in matriz:
        # Elimino los duplicados de cada fila y los paso de objeto array a elemento de array(tolist)
        aux.append((np.unique(fila)).tolist())
    return aux

# Sin elementos repetidos en toda la matriz
def eliminarDuplicadosMatriz2(matriz):
    return np.unique(matriz)

    
print(eliminarDuplicadosMatriz1([[1,2,3],[4,5,2],[3,4,5],[3,4,5],[4,5,5]]))
print(eliminarDuplicadosMatriz1([['gato', 'pez', 'perro'], ['pez', 'perro', 'gallina'], ['perro', 'gaviota', 'gato']])) 

print(eliminarDuplicadosMatriz2([[1,2,3],[4,5,2],[3,4,5],[3,4,5],[4,5,5]]))
print(eliminarDuplicadosMatriz2([['gato', 'pez', 'perro'], ['pez', 'perro', 'gallina'], ['perro', 'gaviota', 'gato']])) 

[[1, 2, 3], [2, 4, 5], [3, 4, 5], [3, 4, 5], [4, 5]]
[['gato', 'perro', 'pez'], ['gallina', 'perro', 'pez'], ['gato', 'gaviota', 'perro']]
[1 2 3 4 5]
['gallina' 'gato' 'gaviota' 'perro' 'pez']


In [2]:
# Función que recibe una lista y devuelve un diccionario con el número de veces que aparece cada elemento 
# (las claves del diccionario deben ser los elementos de la lista y los valores deben ser el número de veces que aparece 
# dicho elemento en la lista)

import numpy as np

def contarElementos(lista):
    diccionario = {}
    aux = np.array(lista)
    elemento, indice, veces = np.unique(aux, return_index=True, return_counts=True)
    for indice in range(len(elemento)):
        if elemento[indice] not in diccionario:
            diccionario.update({elemento[indice]:veces[indice]})
    return diccionario

print(contarElementos([1,2,3,4,5,2,3,4,5,3,4,5,4,5,5]))
print(contarElementos(['gato', 'pez', 'perro', 'pez', 'perro', 'gallina', 'perro']))

{1: 1, 2: 2, 3: 3, 4: 4, 5: 5}
{'gallina': 1, 'gato': 1, 'perro': 3, 'pez': 2}


In [13]:
# Función que recibe dos matrices cuadradas (NxN) y devuelve una tercera matriz que contiene el valor 1 en las posiciones en que el valor de A y B coinciden y 0 en caso contrario.
import numpy as np

def valores_iguales_matriz(matriz1, matriz2):
    aux = np.zeros((len(matriz1), len(matriz1)))
    aux = np.where(np.array(matriz1) == np.array(matriz2), 1, aux)
    return aux

# Tests
matriz1 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] # Matriz 3x3
matriz2 = [[1, 5, 6], [7, 5, 9], [1, 2, 9]] # Matriz 3x3
print(valores_iguales_matriz(matriz1, matriz2)) # Debería mostrar una matriz identidad
# assert valores_iguales_matriz(matriz1, matriz2) == [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
'''
La sentencia assert evalúa una expresión booleana. Si es True, no hace nada. Si es False, lanza una excepción de tipo AssertionError.
Si tu función es correcta, al ejecutar no debería mostrar nada. Si falla, mostrará un AssertionError.
Se utiliza para testing. 
https://ellibrodepython.com/assert-python
'''


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


'\nLa sentencia assert evalúa una expresión booleana. Si es True, no hace nada. Si es False, lanza una excepción de tipo AssertionError.\nSi tu función es correcta, al ejecutar no debería mostrar nada. Si falla, mostrará un AssertionError.\nSe utiliza para testing. \nhttps://ellibrodepython.com/assert-python\n'

In [14]:
# Función que recibe una matriz y busca sus puntos de silla (mínimo de su fila y máximo de su columna o viceversa). 
# Debe devolver una lista de tuplas con las coordenadas de los puntos de silla.
import numpy as np

def hallarPSilla(matriz):
    puntosSilla = []
    aux = np.array(matriz)
    for fila in range(aux.shape[0]):
        for columna in range(aux.shape[1]):
            if (aux[fila,columna] == np.min(aux[fila,:]) and aux[fila,columna] == np.max(aux[:,columna])) or (
                aux[fila,columna] == np.max(aux[fila,:]) and aux[fila,columna] == np.min(aux[:,columna])):
                puntosSilla.append((fila,columna))
    return puntosSilla

print(hallarPSilla([[1,2,3],
                    [4,5,2],
                    [3,4,5],
                    [3,4,5],
                    [4,5,5]]))
print(hallarPSilla([[1,4,3,3,4],
                    [2,5,4,4,5],
                    [3,2,5,5,5]]))
print(hallarPSilla([[1,2,6],
                    [4,5,5],
                    [3,4,5],
                    [3,4,5],
                    [4,5,5]]))
print(hallarPSilla([[1,4,3,3,4],
                    [2,5,4,4,5],
                    [6,5,5,5,5]]))

[(4, 0)]
[(0, 4)]
[(1, 0), (1, 2), (2, 2), (3, 2), (4, 0), (4, 2)]
[(0, 1), (0, 4), (2, 1), (2, 2), (2, 3), (2, 4)]


## 

## 